name: build armv7
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Commit on the given branch to build"
        required: true

jobs:
  build:
    name: "ARMv7 engines build on tag ${{ github.event.inputs.tag }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.inputs.tag }}
        uses: actions/checkout@v3
        with:
          repository: 'prisma/prisma-engines'
          ref: ${{ github.event.inputs.tag }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup cross with custom image
        run: |-
          cat <<EOF > Cross.toml
            [target.armv7-unknown-linux-gnueabihf]
            image = "benoit485/prisma-engine-rpi-build"
          EOF
      
      - name: List files for verification
        run: ls -al && cat Cross.toml
           
      - name: Install cross & Build query-engine
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --release -p query-engine
             
      - name: Build query-engine-node-api
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --release -p query-engine-node-api
             
      - name: Build prisma-fmt
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --release -p prisma-fmt
             
      - name: Build migration-engine-cli
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --release -p migration-engine-cli
             
      - name: Build introspection-core
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --release -p introspection-core
      - name: Rename Node API file
        run: |
          mv ${{ github.workspace }}/target/armv7-unknown-linux-gnueabihf/release/libquery_engine.so ${{ github.workspace }}/target/armv7-unknown-linux-gnueabihf/release/libquery_engine_napi.so.node
      - name: Copy release files
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          commit: master
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "Automatic release via CI: ${{ github.event.inputs.tag }}"
          artifacts: |
            ${{ github.workspace }}/target/armv7-unknown-linux-gnueabihf/release/query-engine
            ${{ github.workspace }}/target/armv7-unknown-linux-gnueabihf/release/prisma-fmt
            ${{ github.workspace }}/target/armv7-unknown-linux-gnueabihf/release/migration-engine
            ${{ github.workspace }}/target/armv7-unknown-linux-gnueabihf/release/introspection-engine
            ${{ github.workspace }}/target/armv7-unknown-linux-gnueabihf/release/libquery_engine_napi.so.node

